language: android
android:
  components:
    - tools
    - platform-tools
    - tools

before_install:
  - yes | sdkmanager "platforms;android-27" "build-tools;27.0.3"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - ./gradlew build
