language: android
jdk:
    - oraclejdk8
android:
  components:
    # The BuildTools version used by MaterialFBook
    - tools
    - build-tools-25.0.2

    # The SDK version used to compile MaterialFBook
    - android-25

    # Additional components
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Emulators
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-15

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 by default)
    - GRADLE_OPTS=-Xmx1024m # give gradle more memory since it seem to fail otherwise
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew --info build connectedCheck

licenses:
  - '.+'
