version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: androidx.fragment:fragment-ktx
    versions:
    - 1.3.1
    - 1.3.2
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.21-2
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.32
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
  - dependency-name: junit:junit
    versions:
    - 4.13.1
    - 4.13.2
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
